name: CI
on:
  - push
  - pull_request
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Zig
        run: |
          sudo apt install xz-utils
          sudo sh -c 'wget -c https://pkg.machengine.org/zig/zig-linux-x86_64-0.12.0-dev.389+61b70778b.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
      - name: build
        run: zig build
      # - name: test
      #   run: zig build test
  x86_64-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Zig
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://pkg.machengine.org/zig/zig-windows-x86_64-0.12.0-dev.389+61b70778b.zip" -OutFile "C:\zig.zip"
          cd C:\
          7z x zig.zip
          Add-Content $env:GITHUB_PATH "C:\zig-windows-x86_64-0.12.0-dev.389+61b70778b\"
      - name: build
        run: zig build
      # - name: test
      #   run: zig build test
  x86_64-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Zig
        run: |
          brew install xz
          sudo sh -c 'wget -c https://pkg.machengine.org/zig/zig-macos-x86_64-0.12.0-dev.389+61b70778b.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
      - name: build
        run: zig build
      # - name: test
      #   run: zig build test
